#!/usr/bin/env bash

set -e

# Download ansible requirements.
mkdir -p vendor/roles
ansible-galaxy install -r requirements.yml --roles-path vendor/roles

ansible-playbook playbook.yml --ask-become-pass "$@"
