#!/usr/bin/env bash

set -e

################## Variables ###################################################

# Packages required for script to run.
MISSING_PREREQUISITES=()

[ ! -x "$(command -v git)" ] && MISSING_PREREQUISITES+=("git")
[ ! -x "$(command -v ansible)" ] && MISSING_PREREQUISITES+=("ansible")
[ ! -x "$(command -v curl)" ] && MISSING_PREREQUISITES+=("curl")

# If missing prerequisites is not empty.
if (( ${#MISSING_PREREQUISITES[@]} )); then
  green=`tput setaf 2`
  yellow=`tput setaf 3`
  reset=`tput sgr0`
  echo "${green}Installing prerequisite apt packages: ${yellow}${MISSING_PREREQUISITES[*]}${reset}"
  sudo dnf install -y ${MISSING_PREREQUISITES[*]}
fi

# Download dotfiles as git submodules.
git submodule init
git submodule update --remote --force dotfiles

ansible-playbook playbook.yml --ask-become-pass "$@"
