#!/usr/bin/env bash

set -e

# Disable cowsay output.
export ANSIBLE_NOCOWS=1

# Download ansible requirements.
mkdir -p vendor/roles
ansible-galaxy install -r requirements.yml --roles-path vendor/roles

ansible-playbook playbook.yml --diff --ask-become-pass "$@"
