---

roles:
  - name: aws-cli
    src: deekayen.awscli2

  - name: docker
    src: haxorof.docker_ce
    #src: https://github.com/haxorof/ansible-role-docker-ce

  - name: docksal
    src: https://github.com/alexander-danilenko/ansible-role-docksal

  - name: google_cloud_cli
    src: https://github.com/alexander-danilenko/ansible-role-fedora-google-cloud-cli

  - name: jetbrains-toolbox
    src: webarchitect609.jet_brains_toolbox

  - name: node
    src: https://github.com/alexander-danilenko/ansible-role-node

  - name: php-composer
    src: https://github.com/alexander-danilenko/ansible-role-php-composer

  - name: rpmfusion
    src: https://github.com/robertdebock/ansible-role-rpmfusion

  - name: visual-studio-code
    src: gantsign.visual-studio-code

  - name: fish
    src: https://github.com/alexander-danilenko/ansible-role-fish-omf
