---

- name: 'Configure sysctl'
  become: true
  loop: '{{ sysctl_config | default({}) | dict2items }}'
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^{{ item.key }}'
    line: '{{ item.key }}={{ item.value }}'
  register: sysctl
  tags:
    - sysctl

- name: 'Read new values from sysctl.conf'
  become: true
  when: sysctl.changed
  shell: 'sysctl -p'
  args:
    executable: '/bin/bash'
  tags:
    - sysctl

