---

- name: 'Install Python3'
  become: true
  package:
    state: present
    name:
      - 'python3'
      - 'python3-pip'
      - 'python3-virtualenv'

- name: 'Install Python pip3 global packages'
  when: python3_pip3_global_packages|length > 0
  shell: 'pip3 install --user {{ python3_pip3_global_packages | join(" ") }}'
  args:
    executable: '/bin/bash'
