- name: 'Update dnf config'
  become: yes
  loop: '{{ apps_dnf_config | default({}) | dict2items }}'
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^{{ item.key }}'
    line: '{{ item.key }}={{ item.value }}'

- name: 'Make sure directory for *.rpm files exists'
  file:
    path: '{{ apps_rpm_dir }}'
    state: directory
    mode: '0755'

- name: 'Download *.rpm files by URLs'
  when: 
  loop: '{{ apps_rpm_urls | default({}) | dict2items }}'
  get_url:
    url: '{{ item.value }}'
    dest: '{{ apps_rpm_dir }}/{{ item.key }}.rpm'
    mode: '0755'

- name: 'Install all *.rpm files from {{ apps_rpm_dir }}'
  become: yes
  dnf:
    name: "{{ lookup('fileglob', '{{ apps_rpm_dir }}/*.rpm') }}"
    state: present
    disable_gpg_check: true

- name: 'Install dnf packages'
  become: yes
  dnf:
    name: '{{ apps_packages }}'
    state: 'present'
    update_cache: yes

- name: 'Flatpak tasks'
  when: apps_flatpak_packages | length > 0
  include_tasks: 'flatpak.yml'
